export const PATH = {
  MAIN: '/',
  HOMEPAGE: 'home',
  TOPICS: 'topics',
  NOTIFICATION: 'notification',
  SETTINGS: 'settings',
  INFO: 'info',
  CHAT: 'chat/:title',
  LOGIN: '/login',
  REGISTER: '/register',
  SUCCESS_SIGNUP: '/success-signup',
  VERIFICATION_EMAIL: '/verification-email',
  FORGOT_PASSWORD: '/forgot-password',
  RECOVERY_PASSWORD: '/recovery-password',
};
