export const PATH = {
  CHAT: 'chat/:title',
  FORGOT_PASSWORD: '/forgot-password',
  HOMEPAGE: 'home',
  INFO: 'info',
  LOGIN: '/login',
  MAIN: '/',
  NOTIFICATION: 'notification',
  NOT_FOUND: '*',
  REGISTER: '/register',
  RECOVERY_PASSWORD: '/recovery-password',
  SETTINGS: 'settings',
  SUCCESS_SIGNUP: '/success-signup',
  TOPICS: 'topics',
  VERIFICATION_EMAIL: '/verification-email',
};
